---
- name: Install required packages
  apt:
    state: present
    name:
      - adequate
      - apt-cacher-ng
      - check-all-the-things
      - debian-keyring
      - debootstrap
      - devscripts
      - dh-cargo
      - dose-extra
      - dpkg-dev-el
      - freight
      - git
      - git-buildpackage
      - gnupg2
      - libconfig-model-dpkg-perl  # Provides scan-copyrights
      - libdistro-info-perl
      - liburi-perl
      - libwww-perl
      - lintian
      - meld
      - piuparts
      - pkg-perl-tools
      - pristine-tar
      - ratt
      - reportbug
      - sbuild
      - schroot
  become: yes

