---
- name: "ZFS : Create main dataset"
  become: yes
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}"
    state: present
    extra_zfs_properties:
      compression: lz4
      mountpoint: "{{ debian__path }}"

- name: "ZFS : Create datasets"
  become: yes
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}/{{ item.key }}"
    state: present
    extra_zfs_properties: "{{ item.value }}"
  with_dict:
    buildarea: {}
    cache: {}
    schroot:
      dedup: yes
  loop_control:
    label: "{{ item.key }}"

- name: "ZFS : Create datasets for schroots"
  become: yes
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}/schroot/{{ item_name }}"
    state: present
  with_items: "{{ debian__schroots }}"
  loop_control:
    label: "{{ item_name }}"
